client_config_backend: file
client_config:
    client_id: 137654403041-3qolvte8ohpt0etcrv2le73t29m94vca.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive